"""Golden case (e): the construction funding circularity.

The test that matters here is *internal consistency*: interest recomputed from
the reported drawdown schedule must equal the IDC that was added to project
cost. If those two disagree, the circularity has not actually been solved - it
has been approximated, and the total project cost is a plug.
"""

from __future__ import annotations

import pytest

from engine.circularity import simulate_construction, solve_funding
from engine.defaults import MONTHS_PER_YEAR
from engine.models import DebtTerms, ProjectInputs, SizingConstraint, TaxTreatment
from tests.conftest import CENT

TOLERANCE = 1e-6


def test_idc_is_internally_consistent_with_the_drawdown_schedule(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    """Recompute interest month by month from the reported draws and balances.

    The engine's convention is: draws land at the start of the month, interest
    accrues on the post-draw balance, and interest and commitment fee are both
    capitalised. Reproducing that from the published series must return the
    published IDC to the cent.
    """
    solution = solve_funding(flat_project, base_terms)
    c = solution.construction
    monthly_rate = base_terms.interest_rate / MONTHS_PER_YEAR
    monthly_commitment = base_terms.commitment_fee / MONTHS_PER_YEAR

    balance = 0.0
    recomputed_idc = 0.0
    recomputed_commitment = 0.0
    for m in range(len(c.monthly_debt_draw)):
        after_draw = balance + c.monthly_debt_draw[m]
        interest = after_draw * monthly_rate
        commitment = max(c.debt_at_cod - after_draw, 0.0) * monthly_commitment
        balance = after_draw + interest + commitment
        recomputed_idc += interest
        recomputed_commitment += commitment
        assert balance == pytest.approx(c.monthly_closing_balance[m], abs=CENT)

    assert recomputed_idc == pytest.approx(c.idc, abs=CENT)
    assert recomputed_commitment == pytest.approx(c.commitment_fee, abs=CENT)
    assert balance == pytest.approx(c.debt_at_cod, abs=CENT)


def test_total_project_cost_reconciles_to_its_components(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    solution = solve_funding(flat_project, base_terms)
    c = solution.construction
    assert c.total_project_cost == pytest.approx(
        c.capex + c.upfront_fee + c.commitment_fee + c.idc + c.dsra_initial,
        abs=CENT,
    )
    assert c.debt_at_cod + c.equity_at_cod == pytest.approx(
        c.total_project_cost, abs=CENT
    )
    assert c.gearing == pytest.approx(c.debt_at_cod / c.total_project_cost, abs=1e-12)


def test_sources_equal_uses_across_the_whole_construction_period(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    """Debt draws + equity draws must fund exactly the capex spent."""
    solution = solve_funding(flat_project, base_terms)
    c = solution.construction
    drawn_for_capex = sum(c.monthly_debt_draw) - c.upfront_fee
    assert drawn_for_capex + sum(c.monthly_equity_draw) == pytest.approx(
        flat_project.capex, abs=CENT
    )
    assert c.debt_at_cod == pytest.approx(
        drawn_for_capex + c.upfront_fee + c.idc + c.commitment_fee, abs=CENT
    )


def test_upfront_fee_is_a_percentage_of_the_solved_facility(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    """The fee is charged on the facility it helped size - the circular bit."""
    solution = solve_funding(flat_project, base_terms)
    c = solution.construction
    assert c.upfront_fee == pytest.approx(
        base_terms.upfront_fee * c.debt_at_cod, abs=CENT
    )


def test_gearing_bound_solution_sits_exactly_on_the_cap(
    flat_project: ProjectInputs
) -> None:
    """The outer fixed point: D = max_gearing x TPC(D), with TPC including the
    IDC generated by D itself."""
    terms = DebtTerms(
        target_dscr=1.15, tenor_years=18.0, interest_rate=0.06, max_gearing=0.70,
        tail_years=2.0, dsra_months=6.0,
    )
    solution = solve_funding(flat_project, terms)
    assert solution.sizing.binding_constraint is SizingConstraint.GEARING
    assert solution.construction.gearing == pytest.approx(0.70, abs=1e-9)
    assert solution.debt_size == pytest.approx(
        0.70 * solution.construction.total_project_cost, abs=CENT
    )
    assert solution.construction.converged
    assert solution.construction.residual <= TOLERANCE * 10


def test_solver_is_deterministic(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    """Brent on a fixed bracket at a fixed tolerance: bit-identical reruns."""
    a = solve_funding(flat_project, base_terms)
    b = solve_funding(flat_project, base_terms)
    assert a.debt_size == b.debt_size
    assert a.construction.idc == b.construction.idc
    assert a.construction.total_project_cost == b.construction.total_project_cost


def test_tolerance_is_exposed_and_respected(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    tight = solve_funding(flat_project, base_terms, tolerance=1e-9)
    loose = solve_funding(flat_project, base_terms, tolerance=1e-2)
    assert tight.construction.converged and loose.construction.converged
    assert tight.debt_size == pytest.approx(loose.debt_size, abs=1.0)
    with pytest.raises(ValueError, match="tolerance must be positive"):
        solve_funding(flat_project, base_terms, tolerance=0.0)


def test_higher_interest_rate_raises_idc_and_total_cost(
    flat_project: ProjectInputs
) -> None:
    low = solve_funding(
        flat_project, DebtTerms(interest_rate=0.04, target_dscr=1.15, max_gearing=0.70)
    )
    high = solve_funding(
        flat_project, DebtTerms(interest_rate=0.09, target_dscr=1.15, max_gearing=0.70)
    )
    assert high.construction.idc > low.construction.idc
    assert high.construction.total_project_cost > low.construction.total_project_cost


def test_longer_construction_raises_idc(flat_project: ProjectInputs) -> None:
    from dataclasses import replace

    short = solve_funding(
        replace(flat_project, construction_months=6),
        DebtTerms(target_dscr=1.15, max_gearing=0.70),
    )
    long = solve_funding(
        replace(flat_project, construction_months=30),
        DebtTerms(target_dscr=1.15, max_gearing=0.70),
    )
    assert long.construction.idc > short.construction.idc


def test_front_loaded_capex_curve_raises_idc(flat_project: ProjectInputs) -> None:
    """Spending early means carrying the balance longer - more IDC."""
    from dataclasses import replace

    months = flat_project.construction_months
    front = tuple(float(months - i) for i in range(months))
    back = tuple(float(i + 1) for i in range(months))
    terms = DebtTerms(target_dscr=1.15, max_gearing=0.70)
    front_loaded = solve_funding(replace(flat_project, capex_curve=front), terms)
    back_loaded = solve_funding(replace(flat_project, capex_curve=back), terms)
    assert front_loaded.construction.idc > back_loaded.construction.idc


def test_zero_construction_period_produces_no_idc(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    from dataclasses import replace

    solution = solve_funding(
        replace(flat_project, construction_months=0), base_terms
    )
    assert solution.construction.idc == 0.0
    assert solution.construction.commitment_fee == 0.0
    assert solution.construction.monthly_debt_draw == ()


def test_debt_funded_dsra_increases_the_facility(
    flat_project: ProjectInputs
) -> None:
    equity_funded = solve_funding(
        flat_project, DebtTerms(target_dscr=1.15, max_gearing=0.70,
                                dsra_debt_funded=False)
    )
    debt_funded = solve_funding(
        flat_project, DebtTerms(target_dscr=1.15, max_gearing=0.70,
                                dsra_debt_funded=True)
    )
    assert debt_funded.construction.dsra_initial > 0
    assert debt_funded.construction.debt_at_cod > 0
    # Same total cost either way; only the funding split moves.
    assert debt_funded.construction.total_project_cost == pytest.approx(
        equity_funded.construction.total_project_cost, rel=1e-3
    )


def test_dsra_initial_matches_six_months_of_first_year_service(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    solution = solve_funding(flat_project, base_terms)
    first_service = solution.sizing.debt.debt_service[0]
    assert solution.construction.dsra_initial == pytest.approx(
        0.5 * first_service, abs=CENT
    )


def test_tax_fixed_point_converges_and_is_reported(
    flat_project: ProjectInputs, base_terms: DebtTerms
) -> None:
    """With FULL tax, CFADS depends on interest which depends on CFADS."""
    from dataclasses import replace

    project = replace(
        flat_project, tax_treatment=TaxTreatment.FULL, tax_rate=0.21
    )
    solution = solve_funding(project, base_terms)
    assert solution.tax_iterations > 0
    assert solution.converged

    # The interest series fed into the tax calculation must be the interest the
    # final schedule actually charges.
    interest = solution.sizing.debt.interest
    rate = base_terms.rate_per_period(project.periods_per_year)
    for i, opening in enumerate(solution.sizing.debt.opening_balance):
        assert interest[i] == pytest.approx(opening * rate, abs=CENT)

    # The interest shield lifts CFADS, so FULL raises more debt than PRE_DEBT.
    pre_debt = solve_funding(
        replace(project, tax_treatment=TaxTreatment.PRE_DEBT), base_terms
    )
    assert solution.debt_size > pre_debt.debt_size


def test_gearing_above_one_is_rejected_at_construction() -> None:
    """A facility cannot exceed total project cost; the input validator says so
    rather than letting the solver return negative equity."""
    with pytest.raises(ValueError, match="max_gearing"):
        DebtTerms(max_gearing=1.10)


def test_full_gearing_leaves_no_equity(flat_project: ProjectInputs) -> None:
    """At a 100% cap the facility funds capex, its own fees, IDC and the DSRA,
    and the sponsor puts in nothing."""
    solution = solve_funding(
        flat_project,
        DebtTerms(target_dscr=1.05, max_gearing=1.0, tenor_years=18.0,
                  interest_rate=0.06),
    )
    assert solution.construction.equity_at_cod == pytest.approx(0.0, abs=1.0)
    assert solution.construction.gearing == pytest.approx(1.0, abs=1e-9)


def test_simulate_construction_is_monotone_in_the_debt_funded_amount() -> None:
    """The inner solve relies on this monotonicity for a unique root."""
    weights = tuple(1 / 12 for _ in range(12))
    previous = -1.0
    for x in (0.0, 10e6, 50e6, 100e6, 150e6):
        result = simulate_construction(
            capex=200e6,
            capex_weights=weights,
            debt_funded_capex=x,
            facility_size=160e6,
            upfront_fee_rate=0.0125,
            commitment_fee_rate=0.005,
            annual_interest_rate=0.06,
            dsra_initial=0.0,
            dsra_debt_funded=False,
        )
        assert result.debt_at_cod > previous
        previous = result.debt_at_cod
